--
-- PostgreSQL database dump
--

\restrict XnDjLtjSSTRTgdtapRtazuzETF1OGekTch4ffr8wHgl8T533hp2mFILcfHG2hfB

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg13+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO zeal;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO zeal;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO zeal;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO zeal;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO zeal;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO zeal;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO zeal;

--
-- Name: documents_apiidempotencyrecord; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.documents_apiidempotencyrecord (
    id bigint NOT NULL,
    key character varying(255) NOT NULL,
    request_hash character varying(64) NOT NULL,
    status_code smallint NOT NULL,
    response_body jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT documents_apiidempotencyrecord_status_code_check CHECK ((status_code >= 0))
);


ALTER TABLE public.documents_apiidempotencyrecord OWNER TO zeal;

--
-- Name: documents_apiidempotencyrecord_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.documents_apiidempotencyrecord ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_apiidempotencyrecord_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents_comment; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.documents_comment (
    id uuid NOT NULL,
    body text NOT NULL,
    is_resolved boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    author_id bigint NOT NULL,
    document_id uuid NOT NULL,
    parent_id uuid,
    CONSTRAINT comment_body_not_empty CHECK ((NOT (body = ''::text)))
);


ALTER TABLE public.documents_comment OWNER TO zeal;

--
-- Name: documents_document; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.documents_document (
    id uuid NOT NULL,
    title character varying(255) NOT NULL,
    content jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    owner_id bigint NOT NULL,
    workspace_id uuid
);


ALTER TABLE public.documents_document OWNER TO zeal;

--
-- Name: documents_document_tags; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.documents_document_tags (
    id bigint NOT NULL,
    document_id uuid NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.documents_document_tags OWNER TO zeal;

--
-- Name: documents_document_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.documents_document_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_document_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents_documentattachment; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.documents_documentattachment (
    id uuid NOT NULL,
    file character varying(100) NOT NULL,
    original_name character varying(255) NOT NULL,
    size bigint NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    document_id uuid NOT NULL,
    uploaded_by_id bigint NOT NULL,
    CONSTRAINT documents_documentattachment_size_check CHECK ((size >= 0))
);


ALTER TABLE public.documents_documentattachment OWNER TO zeal;

--
-- Name: documents_documentmember; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.documents_documentmember (
    id uuid NOT NULL,
    role character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    document_id uuid NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.documents_documentmember OWNER TO zeal;

--
-- Name: documents_documentrevision; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.documents_documentrevision (
    id bigint NOT NULL,
    version bigint NOT NULL,
    title character varying(255) NOT NULL,
    content jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    author_id bigint,
    document_id uuid NOT NULL,
    CONSTRAINT documents_documentrevision_version_check CHECK ((version >= 0))
);


ALTER TABLE public.documents_documentrevision OWNER TO zeal;

--
-- Name: documents_documentrevision_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.documents_documentrevision ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_documentrevision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents_tag; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.documents_tag (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    color character varying(7) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.documents_tag OWNER TO zeal;

--
-- Name: documents_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.documents_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects_activitylog; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.projects_activitylog (
    id bigint NOT NULL,
    action character varying(60) NOT NULL,
    changes jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    actor_id bigint,
    project_id uuid NOT NULL,
    task_id uuid,
    workspace_id uuid NOT NULL
);


ALTER TABLE public.projects_activitylog OWNER TO zeal;

--
-- Name: projects_activitylog_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.projects_activitylog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_activitylog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects_notification; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.projects_notification (
    id uuid NOT NULL,
    kind character varying(50) NOT NULL,
    message character varying(255) NOT NULL,
    target_url character varying(500) NOT NULL,
    read_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    actor_id bigint,
    recipient_id bigint NOT NULL,
    task_id uuid
);


ALTER TABLE public.projects_notification OWNER TO zeal;

--
-- Name: projects_project; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.projects_project (
    id uuid NOT NULL,
    name character varying(150) NOT NULL,
    description text NOT NULL,
    status character varying(12) NOT NULL,
    start_date date,
    due_date date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint NOT NULL,
    team_id uuid,
    workspace_id uuid NOT NULL
);


ALTER TABLE public.projects_project OWNER TO zeal;

--
-- Name: projects_projectmembership; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.projects_projectmembership (
    id uuid NOT NULL,
    role character varying(12) NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    project_id uuid NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.projects_projectmembership OWNER TO zeal;

--
-- Name: projects_task; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.projects_task (
    id uuid NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    status character varying(12) NOT NULL,
    priority character varying(10) NOT NULL,
    start_date date,
    due_date date,
    completed_at timestamp with time zone,
    reminder_sent_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    assignee_id bigint,
    created_by_id bigint NOT NULL,
    project_id uuid NOT NULL
);


ALTER TABLE public.projects_task OWNER TO zeal;

--
-- Name: projects_taskattachment; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.projects_taskattachment (
    id uuid NOT NULL,
    file character varying(100) NOT NULL,
    original_name character varying(255) NOT NULL,
    size bigint NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    task_id uuid NOT NULL,
    uploaded_by_id bigint NOT NULL,
    CONSTRAINT projects_taskattachment_size_check CHECK ((size >= 0))
);


ALTER TABLE public.projects_taskattachment OWNER TO zeal;

--
-- Name: projects_taskcomment; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.projects_taskcomment (
    id uuid NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    author_id bigint NOT NULL,
    task_id uuid NOT NULL,
    CONSTRAINT task_comment_body_not_empty CHECK ((NOT (body = ''::text)))
);


ALTER TABLE public.projects_taskcomment OWNER TO zeal;

--
-- Name: teams_team; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.teams_team (
    id uuid NOT NULL,
    name character varying(120) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint NOT NULL,
    workspace_id uuid NOT NULL
);


ALTER TABLE public.teams_team OWNER TO zeal;

--
-- Name: teams_teammembership; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.teams_teammembership (
    id uuid NOT NULL,
    role character varying(10) NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    team_id uuid NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.teams_teammembership OWNER TO zeal;

--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO zeal;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO zeal;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_emailverification; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.users_emailverification (
    id bigint NOT NULL,
    is_verified boolean NOT NULL,
    verified_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.users_emailverification OWNER TO zeal;

--
-- Name: users_emailverification_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.users_emailverification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_emailverification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_socialaccount; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.users_socialaccount (
    id bigint NOT NULL,
    provider character varying(50) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    metadata jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.users_socialaccount OWNER TO zeal;

--
-- Name: users_socialaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.users_socialaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_socialaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254)
);


ALTER TABLE public.users_user OWNER TO zeal;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO zeal;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO zeal;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_webhookevent; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.users_webhookevent (
    id bigint NOT NULL,
    provider character varying(50) NOT NULL,
    event_id character varying(255) NOT NULL,
    payload jsonb NOT NULL,
    received_at timestamp with time zone NOT NULL,
    processed_at timestamp with time zone
);


ALTER TABLE public.users_webhookevent OWNER TO zeal;

--
-- Name: users_webhookevent_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.users_webhookevent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_webhookevent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspaces_auditlog; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.workspaces_auditlog (
    id bigint NOT NULL,
    action character varying(50) NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id character varying(100) NOT NULL,
    metadata jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    actor_id bigint,
    workspace_id uuid NOT NULL
);


ALTER TABLE public.workspaces_auditlog OWNER TO zeal;

--
-- Name: workspaces_auditlog_id_seq; Type: SEQUENCE; Schema: public; Owner: zeal
--

ALTER TABLE public.workspaces_auditlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspaces_auditlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspaces_workspace; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.workspaces_workspace (
    id uuid NOT NULL,
    name character varying(120) NOT NULL,
    slug character varying(140) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    owner_id bigint NOT NULL
);


ALTER TABLE public.workspaces_workspace OWNER TO zeal;

--
-- Name: workspaces_workspaceinvitation; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.workspaces_workspaceinvitation (
    id uuid NOT NULL,
    email character varying(254) NOT NULL,
    role character varying(10) NOT NULL,
    token_hash character varying(128) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    accepted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    invited_by_id bigint NOT NULL,
    workspace_id uuid NOT NULL
);


ALTER TABLE public.workspaces_workspaceinvitation OWNER TO zeal;

--
-- Name: workspaces_workspacemember; Type: TABLE; Schema: public; Owner: zeal
--

CREATE TABLE public.workspaces_workspacemember (
    id uuid NOT NULL,
    role character varying(10) NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    workspace_id uuid NOT NULL,
    CONSTRAINT valid_workspace_role CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'ADMIN'::character varying, 'MEMBER'::character varying])::text[])))
);


ALTER TABLE public.workspaces_workspacemember OWNER TO zeal;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.auth_group (id, name) FROM stdin;
1	Zeal Owners
2	Zeal Editors
3	Zeal Viewers
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
1	1	45
2	1	46
3	1	47
4	1	48
5	1	49
6	1	50
7	1	51
8	1	52
9	1	53
10	1	54
11	1	55
12	1	56
13	1	57
14	1	58
15	1	59
16	1	60
17	1	61
18	1	62
19	1	63
20	1	64
21	1	65
22	1	66
23	1	67
24	1	68
25	1	69
26	1	70
27	1	71
28	1	72
29	1	73
30	1	74
31	1	75
32	1	76
33	1	77
34	1	78
35	1	79
36	1	80
37	1	81
38	1	82
39	1	83
40	1	84
41	1	85
42	1	86
43	1	87
44	1	88
45	2	64
46	2	62
47	3	64
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Blacklisted Token	6	add_blacklistedtoken
22	Can change Blacklisted Token	6	change_blacklistedtoken
23	Can delete Blacklisted Token	6	delete_blacklistedtoken
24	Can view Blacklisted Token	6	view_blacklistedtoken
25	Can add Outstanding Token	7	add_outstandingtoken
26	Can change Outstanding Token	7	change_outstandingtoken
27	Can delete Outstanding Token	7	delete_outstandingtoken
28	Can view Outstanding Token	7	view_outstandingtoken
29	Can add user	8	add_user
30	Can change user	8	change_user
31	Can delete user	8	delete_user
32	Can view user	8	view_user
33	Can add email verification	9	add_emailverification
34	Can change email verification	9	change_emailverification
35	Can delete email verification	9	delete_emailverification
36	Can view email verification	9	view_emailverification
37	Can add social account	10	add_socialaccount
38	Can change social account	10	change_socialaccount
39	Can delete social account	10	delete_socialaccount
40	Can view social account	10	view_socialaccount
41	Can add webhook event	11	add_webhookevent
42	Can change webhook event	11	change_webhookevent
43	Can delete webhook event	11	delete_webhookevent
44	Can view webhook event	11	view_webhookevent
45	Can add workspace	12	add_workspace
46	Can change workspace	12	change_workspace
47	Can delete workspace	12	delete_workspace
48	Can view workspace	12	view_workspace
49	Can add workspace member	13	add_workspacemember
50	Can change workspace member	13	change_workspacemember
51	Can delete workspace member	13	delete_workspacemember
52	Can view workspace member	13	view_workspacemember
53	Can add workspace invitation	14	add_workspaceinvitation
54	Can change workspace invitation	14	change_workspaceinvitation
55	Can delete workspace invitation	14	delete_workspaceinvitation
56	Can view workspace invitation	14	view_workspaceinvitation
57	Can add audit log	15	add_auditlog
58	Can change audit log	15	change_auditlog
59	Can delete audit log	15	delete_auditlog
60	Can view audit log	15	view_auditlog
61	Can add document	16	add_document
62	Can change document	16	change_document
63	Can delete document	16	delete_document
64	Can view document	16	view_document
65	Can add document member	17	add_documentmember
66	Can change document member	17	change_documentmember
67	Can delete document member	17	delete_documentmember
68	Can view document member	17	view_documentmember
69	Can add tag	18	add_tag
70	Can change tag	18	change_tag
71	Can delete tag	18	delete_tag
72	Can view tag	18	view_tag
73	Can add comment	19	add_comment
74	Can change comment	19	change_comment
75	Can delete comment	19	delete_comment
76	Can view comment	19	view_comment
77	Can add document revision	20	add_documentrevision
78	Can change document revision	20	change_documentrevision
79	Can delete document revision	20	delete_documentrevision
80	Can view document revision	20	view_documentrevision
81	Can add document attachment	21	add_documentattachment
82	Can change document attachment	21	change_documentattachment
83	Can delete document attachment	21	delete_documentattachment
84	Can view document attachment	21	view_documentattachment
85	Can add api idempotency record	22	add_apiidempotencyrecord
86	Can change api idempotency record	22	change_apiidempotencyrecord
87	Can delete api idempotency record	22	delete_apiidempotencyrecord
88	Can view api idempotency record	22	view_apiidempotencyrecord
89	Can add team	23	add_team
90	Can change team	23	change_team
91	Can delete team	23	delete_team
92	Can view team	23	view_team
93	Can add team membership	24	add_teammembership
94	Can change team membership	24	change_teammembership
95	Can delete team membership	24	delete_teammembership
96	Can view team membership	24	view_teammembership
97	Can add activity log	25	add_activitylog
98	Can change activity log	25	change_activitylog
99	Can delete activity log	25	delete_activitylog
100	Can view activity log	25	view_activitylog
101	Can add notification	26	add_notification
102	Can change notification	26	change_notification
103	Can delete notification	26	delete_notification
104	Can view notification	26	view_notification
105	Can add project	27	add_project
106	Can change project	27	change_project
107	Can delete project	27	delete_project
108	Can view project	27	view_project
109	Can add task	28	add_task
110	Can change task	28	change_task
111	Can delete task	28	delete_task
112	Can view task	28	view_task
113	Can add task comment	29	add_taskcomment
114	Can change task comment	29	change_taskcomment
115	Can delete task comment	29	delete_taskcomment
116	Can view task comment	29	view_taskcomment
117	Can add task attachment	30	add_taskattachment
118	Can change task attachment	30	change_taskattachment
119	Can delete task attachment	30	delete_taskattachment
120	Can view task attachment	30	view_taskattachment
121	Can add project membership	31	add_projectmembership
122	Can change project membership	31	change_projectmembership
123	Can delete project membership	31	delete_projectmembership
124	Can view project membership	31	view_projectmembership
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	token_blacklist	blacklistedtoken
7	token_blacklist	outstandingtoken
8	users	user
9	users	emailverification
10	users	socialaccount
11	users	webhookevent
12	workspaces	workspace
13	workspaces	workspacemember
14	workspaces	workspaceinvitation
15	workspaces	auditlog
16	documents	document
17	documents	documentmember
18	documents	tag
19	documents	comment
20	documents	documentrevision
21	documents	documentattachment
22	documents	apiidempotencyrecord
23	teams	team
24	teams	teammembership
25	projects	activitylog
26	projects	notification
27	projects	project
28	projects	task
29	projects	taskcomment
30	projects	taskattachment
31	projects	projectmembership
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-07-29 09:27:46.13646+00
2	contenttypes	0002_remove_content_type_name	2026-07-29 09:27:46.146214+00
3	auth	0001_initial	2026-07-29 09:27:46.167686+00
4	auth	0002_alter_permission_name_max_length	2026-07-29 09:27:46.170859+00
5	auth	0003_alter_user_email_max_length	2026-07-29 09:27:46.174323+00
6	auth	0004_alter_user_username_opts	2026-07-29 09:27:46.177453+00
7	auth	0005_alter_user_last_login_null	2026-07-29 09:27:46.180006+00
8	auth	0006_require_contenttypes_0002	2026-07-29 09:27:46.181873+00
9	auth	0007_alter_validators_add_error_messages	2026-07-29 09:27:46.186323+00
10	auth	0008_alter_user_username_max_length	2026-07-29 09:27:46.192615+00
11	auth	0009_alter_user_last_name_max_length	2026-07-29 09:27:46.197474+00
12	auth	0010_alter_group_name_max_length	2026-07-29 09:27:46.267623+00
13	auth	0011_update_proxy_permissions	2026-07-29 09:27:46.270816+00
14	auth	0012_alter_user_first_name_max_length	2026-07-29 09:27:46.27869+00
15	users	0001_initial	2026-07-29 09:27:46.307163+00
16	admin	0001_initial	2026-07-29 09:27:46.32866+00
17	admin	0002_logentry_remove_auto_add	2026-07-29 09:27:46.337563+00
18	admin	0003_logentry_add_action_flag_choices	2026-07-29 09:27:46.344299+00
19	workspaces	0001_initial	2026-07-29 09:27:46.45265+00
20	documents	0001_initial	2026-07-29 09:27:46.486056+00
21	documents	0002_tag_document_tags	2026-07-29 09:27:46.506962+00
22	documents	0003_comment_documentrevision_document_workspace_and_more	2026-07-29 09:27:46.741539+00
23	documents	0004_documentattachment_apiidempotencyrecord_and_more	2026-07-29 09:27:46.782029+00
24	sessions	0001_initial	2026-07-29 09:27:46.791368+00
25	token_blacklist	0001_initial	2026-07-29 09:27:46.812728+00
26	token_blacklist	0002_outstandingtoken_jti_hex	2026-07-29 09:27:46.82455+00
27	token_blacklist	0003_auto_20171017_2007	2026-07-29 09:27:46.843469+00
28	token_blacklist	0004_auto_20171017_2013	2026-07-29 09:27:46.858494+00
29	token_blacklist	0005_remove_outstandingtoken_jti	2026-07-29 09:27:46.874504+00
30	token_blacklist	0006_auto_20171017_2113	2026-07-29 09:27:46.881498+00
31	token_blacklist	0007_auto_20171017_2214	2026-07-29 09:27:46.922843+00
32	token_blacklist	0008_migrate_to_bigautofield	2026-07-29 09:27:46.953653+00
33	token_blacklist	0010_fix_migrate_to_bigautofield	2026-07-29 09:27:47.006769+00
34	token_blacklist	0011_linearizes_history	2026-07-29 09:27:47.011779+00
35	token_blacklist	0012_alter_outstandingtoken_user	2026-07-29 09:27:47.105301+00
36	token_blacklist	0013_alter_blacklistedtoken_options_and_more	2026-07-29 09:27:47.116633+00
37	users	0002_socialaccount_webhookevent_and_more	2026-07-29 09:27:47.162887+00
38	workspaces	0002_create_personal_workspaces	2026-07-29 09:28:19.205388+00
39	users	0003_alter_user_managers_alter_user_email	2026-07-29 09:31:35.707554+00
40	teams	0001_initial	2026-07-30 06:27:20.105754+00
41	projects	0001_initial	2026-07-30 06:27:20.141949+00
42	projects	0002_initial	2026-07-30 06:27:20.260136+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: documents_apiidempotencyrecord; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.documents_apiidempotencyrecord (id, key, request_hash, status_code, response_body, created_at, user_id) FROM stdin;
\.


--
-- Data for Name: documents_comment; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.documents_comment (id, body, is_resolved, created_at, updated_at, author_id, document_id, parent_id) FROM stdin;
\.


--
-- Data for Name: documents_document; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.documents_document (id, title, content, created_at, updated_at, owner_id, workspace_id) FROM stdin;
bf2fabfd-1933-4856-99de-4fdee987c5f2	Untitled	{"type": "doc", "content": [{"type": "paragraph", "content": [{"text": "hello world", "type": "text"}]}]}	2026-07-29 09:37:13.202279+00	2026-07-29 09:37:19.737623+00	1	01ddf847-fc60-41f9-9365-d51d75f6991e
424b30c4-17ed-4f76-9243-64273619b6e6	Untitled	{"type": "doc", "content": [{"type": "paragraph"}]}	2026-07-30 06:38:20.080282+00	2026-07-30 06:38:20.080296+00	1	4d2c1eb6-0fb1-482d-a822-77d7153b8b42
\.


--
-- Data for Name: documents_document_tags; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.documents_document_tags (id, document_id, tag_id) FROM stdin;
\.


--
-- Data for Name: documents_documentattachment; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.documents_documentattachment (id, file, original_name, size, uploaded_at, document_id, uploaded_by_id) FROM stdin;
\.


--
-- Data for Name: documents_documentmember; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.documents_documentmember (id, role, created_at, document_id, user_id) FROM stdin;
a4ae7829-d126-4834-a425-9520579968ad	OWNER	2026-07-29 09:37:13.204544+00	bf2fabfd-1933-4856-99de-4fdee987c5f2	1
ebbfbf45-5f5a-4ca8-b8ff-ef6e2d26128e	OWNER	2026-07-30 06:38:20.081166+00	424b30c4-17ed-4f76-9243-64273619b6e6	1
\.


--
-- Data for Name: documents_documentrevision; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.documents_documentrevision (id, version, title, content, created_at, author_id, document_id) FROM stdin;
\.


--
-- Data for Name: documents_tag; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.documents_tag (id, name, color, created_at) FROM stdin;
\.


--
-- Data for Name: projects_activitylog; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.projects_activitylog (id, action, changes, created_at, actor_id, project_id, task_id, workspace_id) FROM stdin;
\.


--
-- Data for Name: projects_notification; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.projects_notification (id, kind, message, target_url, read_at, created_at, actor_id, recipient_id, task_id) FROM stdin;
\.


--
-- Data for Name: projects_project; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.projects_project (id, name, description, status, start_date, due_date, created_at, updated_at, created_by_id, team_id, workspace_id) FROM stdin;
\.


--
-- Data for Name: projects_projectmembership; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.projects_projectmembership (id, role, joined_at, project_id, user_id) FROM stdin;
\.


--
-- Data for Name: projects_task; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.projects_task (id, title, description, status, priority, start_date, due_date, completed_at, reminder_sent_at, created_at, updated_at, assignee_id, created_by_id, project_id) FROM stdin;
\.


--
-- Data for Name: projects_taskattachment; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.projects_taskattachment (id, file, original_name, size, uploaded_at, task_id, uploaded_by_id) FROM stdin;
\.


--
-- Data for Name: projects_taskcomment; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.projects_taskcomment (id, body, created_at, updated_at, author_id, task_id) FROM stdin;
\.


--
-- Data for Name: teams_team; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.teams_team (id, name, description, created_at, updated_at, created_by_id, workspace_id) FROM stdin;
\.


--
-- Data for Name: teams_teammembership; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.teams_teammembership (id, role, joined_at, team_id, user_id) FROM stdin;
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NTkyMjU5NywiaWF0IjoxNzg1MzE3Nzk3LCJqdGkiOiIzNjYyMGZhMzlkOTM0M2M4OWFlZjVjMmMzNjRlNjA3NiIsInVzZXJfaWQiOiIxIn0.wVu16fknM6GrD3Xec2M8eEIvf38U_-9u5sm-PYxTbUs	2026-07-29 09:36:37.086603+00	2026-08-05 09:36:37+00	1	36620fa39d9343c89aef5c2c364e6076
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NTkyMjY1NCwiaWF0IjoxNzg1MzE3ODU0LCJqdGkiOiJlZDIwYmIzZGQxNTM0ZGVkODBlNjg5MDMzYTUyYTI3ZiIsInVzZXJfaWQiOiIxIn0.Hsh3RjE6_HdOpFOrf0tRCAqkyU1yg5Bsw3ggSfWeZ8g	2026-07-29 09:37:34.443268+00	2026-08-05 09:37:34+00	1	ed20bb3dd1534ded80e689033a52a27f
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NTk5ODIyNiwiaWF0IjoxNzg1MzkzNDI2LCJqdGkiOiIwMzRlOGRiZWExNzg0MTMxYTI5ZDAzOTVkNDE5NDViNSIsInVzZXJfaWQiOiIxIn0.ULmXIUf_zGr6LB-CdguAr151z6yYnwxN3Z-QLj48t1E	2026-07-30 06:37:06.079783+00	2026-08-06 06:37:06+00	1	034e8dbea1784131a29d0395d41945b5
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NTk5ODU4NiwiaWF0IjoxNzg1MzkzNzg2LCJqdGkiOiI3NTU1ZGJiZjVlMmY0NjFkYjZiMDkwYTA0ZDAzM2Q2MCIsInVzZXJfaWQiOiIxIn0.EZS-Dha-ySI6PJwXS1Hdw6rp1CLo2Ss-mo5_J_wwjS4	2026-07-30 06:43:06.803516+00	2026-08-06 06:43:06+00	1	7555dbbf5e2f461db6b090a04d033d60
\.


--
-- Data for Name: users_emailverification; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.users_emailverification (id, is_verified, verified_at, created_at, updated_at, user_id) FROM stdin;
1	t	2026-07-29 09:36:21.526174+00	2026-07-29 09:35:31.532279+00	2026-07-29 09:36:21.526553+00	1
2	f	\N	2026-07-29 09:38:18.93569+00	2026-07-29 09:38:18.935692+00	2
\.


--
-- Data for Name: users_socialaccount; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.users_socialaccount (id, provider, provider_user_id, metadata, created_at, user_id) FROM stdin;
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, email) FROM stdin;
2	pbkdf2_sha256$600000$FJrc39Ir15lzX4LmA1zrLS$nGml/FnUVWtSY2iQ3CSiWmaYgFHrMSfYaXh55Y1yekQ=	\N	f	user			f	t	2026-07-29 09:38:18.864941+00	arnoldshaju555@gmail.com
1	pbkdf2_sha256$600000$Ji8PvYEwTfDXGiJmiEOCdK$X8tJrXI5zbhnAIPM+8Eixf8EFUSc1j2owRmxEs/FNX8=	\N	f	qwerty			f	t	2026-07-29 09:35:31.473413+00	arnoldshaju75@gmail.com
\.


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: users_webhookevent; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.users_webhookevent (id, provider, event_id, payload, received_at, processed_at) FROM stdin;
\.


--
-- Data for Name: workspaces_auditlog; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.workspaces_auditlog (id, action, entity_type, entity_id, metadata, created_at, actor_id, workspace_id) FROM stdin;
1	WORKSPACE_CREATED	Workspace	01ddf847-fc60-41f9-9365-d51d75f6991e	{"personal": true}	2026-07-29 09:35:31.531749+00	1	01ddf847-fc60-41f9-9365-d51d75f6991e
2	WORKSPACE_CREATED	Workspace	45b67693-ec50-444c-a136-6ebe22af549f	{"personal": true}	2026-07-29 09:38:18.935395+00	2	45b67693-ec50-444c-a136-6ebe22af549f
3	WORKSPACE_CREATED	Workspace	4d2c1eb6-0fb1-482d-a822-77d7153b8b42	{"personal": false}	2026-07-30 06:37:53.102571+00	1	4d2c1eb6-0fb1-482d-a822-77d7153b8b42
\.


--
-- Data for Name: workspaces_workspace; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.workspaces_workspace (id, name, slug, created_at, updated_at, owner_id) FROM stdin;
01ddf847-fc60-41f9-9365-d51d75f6991e	qwerty's Workspace	personal-1	2026-07-29 09:35:31.530223+00	2026-07-29 09:35:31.530228+00	1
45b67693-ec50-444c-a136-6ebe22af549f	user's Workspace	personal-2	2026-07-29 09:38:18.934421+00	2026-07-29 09:38:18.934425+00	2
4d2c1eb6-0fb1-482d-a822-77d7153b8b42	awe	awe	2026-07-30 06:37:53.101791+00	2026-07-30 06:37:53.101801+00	1
\.


--
-- Data for Name: workspaces_workspaceinvitation; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.workspaces_workspaceinvitation (id, email, role, token_hash, expires_at, accepted_at, created_at, invited_by_id, workspace_id) FROM stdin;
\.


--
-- Data for Name: workspaces_workspacemember; Type: TABLE DATA; Schema: public; Owner: zeal
--

COPY public.workspaces_workspacemember (id, role, joined_at, user_id, workspace_id) FROM stdin;
bf5d61c8-3565-446e-b260-375614cc4e99	OWNER	2026-07-29 09:38:18.93512+00	2	45b67693-ec50-444c-a136-6ebe22af549f
8c4b36c4-db8e-4b4c-b692-7b5beed3377a	OWNER	2026-07-30 06:37:53.102206+00	1	4d2c1eb6-0fb1-482d-a822-77d7153b8b42
a2c9b63d-01ea-47ad-8cd0-60f179f67385	OWNER	2026-07-29 09:35:31.531304+00	1	01ddf847-fc60-41f9-9365-d51d75f6991e
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 3, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 47, true);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 124, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 31, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 42, true);


--
-- Name: documents_apiidempotencyrecord_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.documents_apiidempotencyrecord_id_seq', 1, false);


--
-- Name: documents_document_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.documents_document_tags_id_seq', 1, false);


--
-- Name: documents_documentrevision_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.documents_documentrevision_id_seq', 1, false);


--
-- Name: documents_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.documents_tag_id_seq', 1, false);


--
-- Name: projects_activitylog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.projects_activitylog_id_seq', 1, false);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 1, false);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 4, true);


--
-- Name: users_emailverification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.users_emailverification_id_seq', 2, true);


--
-- Name: users_socialaccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.users_socialaccount_id_seq', 1, false);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.users_user_id_seq', 2, true);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- Name: users_webhookevent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.users_webhookevent_id_seq', 1, false);


--
-- Name: workspaces_auditlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zeal
--

SELECT pg_catalog.setval('public.workspaces_auditlog_id_seq', 3, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: documents_apiidempotencyrecord documents_apiidempotencyrecord_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_apiidempotencyrecord
    ADD CONSTRAINT documents_apiidempotencyrecord_pkey PRIMARY KEY (id);


--
-- Name: documents_comment documents_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_comment
    ADD CONSTRAINT documents_comment_pkey PRIMARY KEY (id);


--
-- Name: documents_document documents_document_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_document
    ADD CONSTRAINT documents_document_pkey PRIMARY KEY (id);


--
-- Name: documents_document_tags documents_document_tags_document_id_tag_id_07e90502_uniq; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_document_tags
    ADD CONSTRAINT documents_document_tags_document_id_tag_id_07e90502_uniq UNIQUE (document_id, tag_id);


--
-- Name: documents_document_tags documents_document_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_document_tags
    ADD CONSTRAINT documents_document_tags_pkey PRIMARY KEY (id);


--
-- Name: documents_documentattachment documents_documentattachment_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_documentattachment
    ADD CONSTRAINT documents_documentattachment_pkey PRIMARY KEY (id);


--
-- Name: documents_documentmember documents_documentmember_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_documentmember
    ADD CONSTRAINT documents_documentmember_pkey PRIMARY KEY (id);


--
-- Name: documents_documentrevision documents_documentrevision_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_documentrevision
    ADD CONSTRAINT documents_documentrevision_pkey PRIMARY KEY (id);


--
-- Name: documents_tag documents_tag_name_key; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_tag
    ADD CONSTRAINT documents_tag_name_key UNIQUE (name);


--
-- Name: documents_tag documents_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_tag
    ADD CONSTRAINT documents_tag_pkey PRIMARY KEY (id);


--
-- Name: projects_activitylog projects_activitylog_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_activitylog
    ADD CONSTRAINT projects_activitylog_pkey PRIMARY KEY (id);


--
-- Name: projects_notification projects_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_notification
    ADD CONSTRAINT projects_notification_pkey PRIMARY KEY (id);


--
-- Name: projects_project projects_project_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_pkey PRIMARY KEY (id);


--
-- Name: projects_projectmembership projects_projectmembership_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_projectmembership
    ADD CONSTRAINT projects_projectmembership_pkey PRIMARY KEY (id);


--
-- Name: projects_task projects_task_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_task
    ADD CONSTRAINT projects_task_pkey PRIMARY KEY (id);


--
-- Name: projects_taskattachment projects_taskattachment_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_taskattachment
    ADD CONSTRAINT projects_taskattachment_pkey PRIMARY KEY (id);


--
-- Name: projects_taskcomment projects_taskcomment_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_taskcomment
    ADD CONSTRAINT projects_taskcomment_pkey PRIMARY KEY (id);


--
-- Name: teams_team teams_team_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.teams_team
    ADD CONSTRAINT teams_team_pkey PRIMARY KEY (id);


--
-- Name: teams_teammembership teams_teammembership_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.teams_teammembership
    ADD CONSTRAINT teams_teammembership_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: documents_documentmember unique_document_member; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_documentmember
    ADD CONSTRAINT unique_document_member UNIQUE (document_id, user_id);


--
-- Name: documents_documentrevision unique_document_revision; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_documentrevision
    ADD CONSTRAINT unique_document_revision UNIQUE (document_id, version);


--
-- Name: projects_projectmembership unique_project_member; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_projectmembership
    ADD CONSTRAINT unique_project_member UNIQUE (project_id, user_id);


--
-- Name: projects_project unique_project_name_per_workspace; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT unique_project_name_per_workspace UNIQUE (workspace_id, name);


--
-- Name: users_socialaccount unique_social_provider_account; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_socialaccount
    ADD CONSTRAINT unique_social_provider_account UNIQUE (provider, provider_user_id);


--
-- Name: teams_teammembership unique_team_member; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.teams_teammembership
    ADD CONSTRAINT unique_team_member UNIQUE (team_id, user_id);


--
-- Name: teams_team unique_team_name_per_workspace; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.teams_team
    ADD CONSTRAINT unique_team_name_per_workspace UNIQUE (workspace_id, name);


--
-- Name: documents_apiidempotencyrecord unique_user_idempotency_key; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_apiidempotencyrecord
    ADD CONSTRAINT unique_user_idempotency_key UNIQUE (user_id, key);


--
-- Name: users_webhookevent unique_webhook_event; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_webhookevent
    ADD CONSTRAINT unique_webhook_event UNIQUE (provider, event_id);


--
-- Name: workspaces_workspacemember unique_workspace_member; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_workspacemember
    ADD CONSTRAINT unique_workspace_member UNIQUE (workspace_id, user_id);


--
-- Name: users_emailverification users_emailverification_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_emailverification
    ADD CONSTRAINT users_emailverification_pkey PRIMARY KEY (id);


--
-- Name: users_emailverification users_emailverification_user_id_key; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_emailverification
    ADD CONSTRAINT users_emailverification_user_id_key UNIQUE (user_id);


--
-- Name: users_socialaccount users_socialaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_socialaccount
    ADD CONSTRAINT users_socialaccount_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: users_user users_user_username_key; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);


--
-- Name: users_webhookevent users_webhookevent_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_webhookevent
    ADD CONSTRAINT users_webhookevent_pkey PRIMARY KEY (id);


--
-- Name: workspaces_auditlog workspaces_auditlog_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_auditlog
    ADD CONSTRAINT workspaces_auditlog_pkey PRIMARY KEY (id);


--
-- Name: workspaces_workspace workspaces_workspace_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_workspace
    ADD CONSTRAINT workspaces_workspace_pkey PRIMARY KEY (id);


--
-- Name: workspaces_workspace workspaces_workspace_slug_key; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_workspace
    ADD CONSTRAINT workspaces_workspace_slug_key UNIQUE (slug);


--
-- Name: workspaces_workspaceinvitation workspaces_workspaceinvitation_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_workspaceinvitation
    ADD CONSTRAINT workspaces_workspaceinvitation_pkey PRIMARY KEY (id);


--
-- Name: workspaces_workspaceinvitation workspaces_workspaceinvitation_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_workspaceinvitation
    ADD CONSTRAINT workspaces_workspaceinvitation_token_hash_key UNIQUE (token_hash);


--
-- Name: workspaces_workspacemember workspaces_workspacemember_pkey; Type: CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_workspacemember
    ADD CONSTRAINT workspaces_workspacemember_pkey PRIMARY KEY (id);


--
-- Name: audit_entity_idx; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX audit_entity_idx ON public.workspaces_auditlog USING btree (entity_type, entity_id);


--
-- Name: audit_workspace_time_idx; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX audit_workspace_time_idx ON public.workspaces_auditlog USING btree (workspace_id, created_at DESC);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: comment_doc_state_idx; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX comment_doc_state_idx ON public.documents_comment USING btree (document_id, is_resolved, created_at DESC);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: doc_owner_time_idx; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX doc_owner_time_idx ON public.documents_document USING btree (owner_id, updated_at DESC);


--
-- Name: doc_workspace_time_idx; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX doc_workspace_time_idx ON public.documents_document USING btree (workspace_id, updated_at DESC);


--
-- Name: documents_apiidempotencyrecord_user_id_23eecfbc; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_apiidempotencyrecord_user_id_23eecfbc ON public.documents_apiidempotencyrecord USING btree (user_id);


--
-- Name: documents_comment_author_id_2c5ec72f; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_comment_author_id_2c5ec72f ON public.documents_comment USING btree (author_id);


--
-- Name: documents_comment_document_id_3f5d21c7; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_comment_document_id_3f5d21c7 ON public.documents_comment USING btree (document_id);


--
-- Name: documents_comment_parent_id_67c7fb92; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_comment_parent_id_67c7fb92 ON public.documents_comment USING btree (parent_id);


--
-- Name: documents_document_owner_id_04d2b723; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_document_owner_id_04d2b723 ON public.documents_document USING btree (owner_id);


--
-- Name: documents_document_tags_document_id_006f35a8; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_document_tags_document_id_006f35a8 ON public.documents_document_tags USING btree (document_id);


--
-- Name: documents_document_tags_tag_id_4f4a71e9; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_document_tags_tag_id_4f4a71e9 ON public.documents_document_tags USING btree (tag_id);


--
-- Name: documents_document_workspace_id_75c69096; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_document_workspace_id_75c69096 ON public.documents_document USING btree (workspace_id);


--
-- Name: documents_documentattachment_document_id_d235dfef; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_documentattachment_document_id_d235dfef ON public.documents_documentattachment USING btree (document_id);


--
-- Name: documents_documentattachment_uploaded_by_id_26386a77; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_documentattachment_uploaded_by_id_26386a77 ON public.documents_documentattachment USING btree (uploaded_by_id);


--
-- Name: documents_documentmember_document_id_de0fa76c; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_documentmember_document_id_de0fa76c ON public.documents_documentmember USING btree (document_id);


--
-- Name: documents_documentmember_user_id_131457ee; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_documentmember_user_id_131457ee ON public.documents_documentmember USING btree (user_id);


--
-- Name: documents_documentrevision_author_id_b75db0cf; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_documentrevision_author_id_b75db0cf ON public.documents_documentrevision USING btree (author_id);


--
-- Name: documents_documentrevision_document_id_f5055c27; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_documentrevision_document_id_f5055c27 ON public.documents_documentrevision USING btree (document_id);


--
-- Name: documents_tag_name_b751fdae_like; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX documents_tag_name_b751fdae_like ON public.documents_tag USING btree (name varchar_pattern_ops);


--
-- Name: notification_recipient_idx; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX notification_recipient_idx ON public.projects_notification USING btree (recipient_id, read_at, created_at DESC);


--
-- Name: project_activity_time_idx; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX project_activity_time_idx ON public.projects_activitylog USING btree (project_id, created_at DESC);


--
-- Name: project_workspace_state_idx; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX project_workspace_state_idx ON public.projects_project USING btree (workspace_id, status, updated_at DESC);


--
-- Name: projects_activitylog_actor_id_fe8c9b10; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_activitylog_actor_id_fe8c9b10 ON public.projects_activitylog USING btree (actor_id);


--
-- Name: projects_activitylog_project_id_c8e588f7; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_activitylog_project_id_c8e588f7 ON public.projects_activitylog USING btree (project_id);


--
-- Name: projects_activitylog_task_id_0d91b7eb; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_activitylog_task_id_0d91b7eb ON public.projects_activitylog USING btree (task_id);


--
-- Name: projects_activitylog_workspace_id_f84cc264; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_activitylog_workspace_id_f84cc264 ON public.projects_activitylog USING btree (workspace_id);


--
-- Name: projects_notification_actor_id_91805d60; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_notification_actor_id_91805d60 ON public.projects_notification USING btree (actor_id);


--
-- Name: projects_notification_recipient_id_2c2dec7a; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_notification_recipient_id_2c2dec7a ON public.projects_notification USING btree (recipient_id);


--
-- Name: projects_notification_task_id_45f7c6b4; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_notification_task_id_45f7c6b4 ON public.projects_notification USING btree (task_id);


--
-- Name: projects_project_created_by_id_c49d7b6d; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_project_created_by_id_c49d7b6d ON public.projects_project USING btree (created_by_id);


--
-- Name: projects_project_team_id_aa0ab9c0; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_project_team_id_aa0ab9c0 ON public.projects_project USING btree (team_id);


--
-- Name: projects_project_workspace_id_7ea54f67; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_project_workspace_id_7ea54f67 ON public.projects_project USING btree (workspace_id);


--
-- Name: projects_projectmembership_project_id_ec39ff46; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_projectmembership_project_id_ec39ff46 ON public.projects_projectmembership USING btree (project_id);


--
-- Name: projects_projectmembership_user_id_aed8d123; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_projectmembership_user_id_aed8d123 ON public.projects_projectmembership USING btree (user_id);


--
-- Name: projects_task_assignee_id_5061de72; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_task_assignee_id_5061de72 ON public.projects_task USING btree (assignee_id);


--
-- Name: projects_task_created_by_id_3dc419bd; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_task_created_by_id_3dc419bd ON public.projects_task USING btree (created_by_id);


--
-- Name: projects_task_project_id_a1b987d6; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_task_project_id_a1b987d6 ON public.projects_task USING btree (project_id);


--
-- Name: projects_taskattachment_task_id_70f581ad; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_taskattachment_task_id_70f581ad ON public.projects_taskattachment USING btree (task_id);


--
-- Name: projects_taskattachment_uploaded_by_id_57bed9e1; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_taskattachment_uploaded_by_id_57bed9e1 ON public.projects_taskattachment USING btree (uploaded_by_id);


--
-- Name: projects_taskcomment_author_id_464e8986; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_taskcomment_author_id_464e8986 ON public.projects_taskcomment USING btree (author_id);


--
-- Name: projects_taskcomment_task_id_3c75a98e; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX projects_taskcomment_task_id_3c75a98e ON public.projects_taskcomment USING btree (task_id);


--
-- Name: revision_doc_version_idx; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX revision_doc_version_idx ON public.documents_documentrevision USING btree (document_id, version DESC);


--
-- Name: task_assignee_state_idx; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX task_assignee_state_idx ON public.projects_task USING btree (assignee_id, status, due_date);


--
-- Name: task_project_state_due_idx; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX task_project_state_due_idx ON public.projects_task USING btree (project_id, status, due_date);


--
-- Name: teams_team_created_by_id_4d452be8; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX teams_team_created_by_id_4d452be8 ON public.teams_team USING btree (created_by_id);


--
-- Name: teams_team_workspace_id_1c116fee; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX teams_team_workspace_id_1c116fee ON public.teams_team USING btree (workspace_id);


--
-- Name: teams_teammembership_team_id_2ee7a456; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX teams_teammembership_team_id_2ee7a456 ON public.teams_teammembership USING btree (team_id);


--
-- Name: teams_teammembership_user_id_0cb613d1; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX teams_teammembership_user_id_0cb613d1 ON public.teams_teammembership USING btree (user_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: unique_pending_workspace_invitation; Type: INDEX; Schema: public; Owner: zeal
--

CREATE UNIQUE INDEX unique_pending_workspace_invitation ON public.workspaces_workspaceinvitation USING btree (workspace_id, email) WHERE (accepted_at IS NULL);


--
-- Name: users_socialaccount_user_id_986a64c3; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX users_socialaccount_user_id_986a64c3 ON public.users_socialaccount USING btree (user_id);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: users_user_username_06e46fe6_like; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);


--
-- Name: workspaces_auditlog_actor_id_bb4bcbea; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX workspaces_auditlog_actor_id_bb4bcbea ON public.workspaces_auditlog USING btree (actor_id);


--
-- Name: workspaces_auditlog_workspace_id_4ad0271b; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX workspaces_auditlog_workspace_id_4ad0271b ON public.workspaces_auditlog USING btree (workspace_id);


--
-- Name: workspaces_workspace_owner_id_d8b120c0; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX workspaces_workspace_owner_id_d8b120c0 ON public.workspaces_workspace USING btree (owner_id);


--
-- Name: workspaces_workspace_slug_c37054a2_like; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX workspaces_workspace_slug_c37054a2_like ON public.workspaces_workspace USING btree (slug varchar_pattern_ops);


--
-- Name: workspaces_workspaceinvitation_invited_by_id_9d28f43e; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX workspaces_workspaceinvitation_invited_by_id_9d28f43e ON public.workspaces_workspaceinvitation USING btree (invited_by_id);


--
-- Name: workspaces_workspaceinvitation_token_hash_ca736892_like; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX workspaces_workspaceinvitation_token_hash_ca736892_like ON public.workspaces_workspaceinvitation USING btree (token_hash varchar_pattern_ops);


--
-- Name: workspaces_workspaceinvitation_workspace_id_dcec2b3d; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX workspaces_workspaceinvitation_workspace_id_dcec2b3d ON public.workspaces_workspaceinvitation USING btree (workspace_id);


--
-- Name: workspaces_workspacemember_user_id_e5e4373e; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX workspaces_workspacemember_user_id_e5e4373e ON public.workspaces_workspacemember USING btree (user_id);


--
-- Name: workspaces_workspacemember_workspace_id_60079244; Type: INDEX; Schema: public; Owner: zeal
--

CREATE INDEX workspaces_workspacemember_workspace_id_60079244 ON public.workspaces_workspacemember USING btree (workspace_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_apiidempotencyrecord documents_apiidempot_user_id_23eecfbc_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_apiidempotencyrecord
    ADD CONSTRAINT documents_apiidempot_user_id_23eecfbc_fk_users_use FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_comment documents_comment_author_id_2c5ec72f_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_comment
    ADD CONSTRAINT documents_comment_author_id_2c5ec72f_fk_users_user_id FOREIGN KEY (author_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_comment documents_comment_document_id_3f5d21c7_fk_documents_document_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_comment
    ADD CONSTRAINT documents_comment_document_id_3f5d21c7_fk_documents_document_id FOREIGN KEY (document_id) REFERENCES public.documents_document(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_comment documents_comment_parent_id_67c7fb92_fk_documents_comment_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_comment
    ADD CONSTRAINT documents_comment_parent_id_67c7fb92_fk_documents_comment_id FOREIGN KEY (parent_id) REFERENCES public.documents_comment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_document documents_document_owner_id_04d2b723_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_document
    ADD CONSTRAINT documents_document_owner_id_04d2b723_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_document_tags documents_document_t_document_id_006f35a8_fk_documents; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_document_tags
    ADD CONSTRAINT documents_document_t_document_id_006f35a8_fk_documents FOREIGN KEY (document_id) REFERENCES public.documents_document(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_document_tags documents_document_tags_tag_id_4f4a71e9_fk_documents_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_document_tags
    ADD CONSTRAINT documents_document_tags_tag_id_4f4a71e9_fk_documents_tag_id FOREIGN KEY (tag_id) REFERENCES public.documents_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_document documents_document_workspace_id_75c69096_fk_workspace; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_document
    ADD CONSTRAINT documents_document_workspace_id_75c69096_fk_workspace FOREIGN KEY (workspace_id) REFERENCES public.workspaces_workspace(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_documentattachment documents_documentat_document_id_d235dfef_fk_documents; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_documentattachment
    ADD CONSTRAINT documents_documentat_document_id_d235dfef_fk_documents FOREIGN KEY (document_id) REFERENCES public.documents_document(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_documentattachment documents_documentat_uploaded_by_id_26386a77_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_documentattachment
    ADD CONSTRAINT documents_documentat_uploaded_by_id_26386a77_fk_users_use FOREIGN KEY (uploaded_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_documentmember documents_documentme_document_id_de0fa76c_fk_documents; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_documentmember
    ADD CONSTRAINT documents_documentme_document_id_de0fa76c_fk_documents FOREIGN KEY (document_id) REFERENCES public.documents_document(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_documentmember documents_documentmember_user_id_131457ee_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_documentmember
    ADD CONSTRAINT documents_documentmember_user_id_131457ee_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_documentrevision documents_documentre_document_id_f5055c27_fk_documents; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_documentrevision
    ADD CONSTRAINT documents_documentre_document_id_f5055c27_fk_documents FOREIGN KEY (document_id) REFERENCES public.documents_document(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_documentrevision documents_documentrevision_author_id_b75db0cf_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.documents_documentrevision
    ADD CONSTRAINT documents_documentrevision_author_id_b75db0cf_fk_users_user_id FOREIGN KEY (author_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_activitylog projects_activitylog_actor_id_fe8c9b10_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_activitylog
    ADD CONSTRAINT projects_activitylog_actor_id_fe8c9b10_fk_users_user_id FOREIGN KEY (actor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_activitylog projects_activitylog_project_id_c8e588f7_fk_projects_project_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_activitylog
    ADD CONSTRAINT projects_activitylog_project_id_c8e588f7_fk_projects_project_id FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_activitylog projects_activitylog_task_id_0d91b7eb_fk_projects_task_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_activitylog
    ADD CONSTRAINT projects_activitylog_task_id_0d91b7eb_fk_projects_task_id FOREIGN KEY (task_id) REFERENCES public.projects_task(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_activitylog projects_activitylog_workspace_id_f84cc264_fk_workspace; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_activitylog
    ADD CONSTRAINT projects_activitylog_workspace_id_f84cc264_fk_workspace FOREIGN KEY (workspace_id) REFERENCES public.workspaces_workspace(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_notification projects_notification_actor_id_91805d60_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_notification
    ADD CONSTRAINT projects_notification_actor_id_91805d60_fk_users_user_id FOREIGN KEY (actor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_notification projects_notification_recipient_id_2c2dec7a_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_notification
    ADD CONSTRAINT projects_notification_recipient_id_2c2dec7a_fk_users_user_id FOREIGN KEY (recipient_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_notification projects_notification_task_id_45f7c6b4_fk_projects_task_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_notification
    ADD CONSTRAINT projects_notification_task_id_45f7c6b4_fk_projects_task_id FOREIGN KEY (task_id) REFERENCES public.projects_task(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_project projects_project_created_by_id_c49d7b6d_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_created_by_id_c49d7b6d_fk_users_user_id FOREIGN KEY (created_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_project projects_project_team_id_aa0ab9c0_fk_teams_team_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_team_id_aa0ab9c0_fk_teams_team_id FOREIGN KEY (team_id) REFERENCES public.teams_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_project projects_project_workspace_id_7ea54f67_fk_workspace; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_workspace_id_7ea54f67_fk_workspace FOREIGN KEY (workspace_id) REFERENCES public.workspaces_workspace(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_projectmembership projects_projectmemb_project_id_ec39ff46_fk_projects_; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_projectmembership
    ADD CONSTRAINT projects_projectmemb_project_id_ec39ff46_fk_projects_ FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_projectmembership projects_projectmembership_user_id_aed8d123_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_projectmembership
    ADD CONSTRAINT projects_projectmembership_user_id_aed8d123_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_task projects_task_assignee_id_5061de72_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_task
    ADD CONSTRAINT projects_task_assignee_id_5061de72_fk_users_user_id FOREIGN KEY (assignee_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_task projects_task_created_by_id_3dc419bd_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_task
    ADD CONSTRAINT projects_task_created_by_id_3dc419bd_fk_users_user_id FOREIGN KEY (created_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_task projects_task_project_id_a1b987d6_fk_projects_project_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_task
    ADD CONSTRAINT projects_task_project_id_a1b987d6_fk_projects_project_id FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_taskattachment projects_taskattachm_uploaded_by_id_57bed9e1_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_taskattachment
    ADD CONSTRAINT projects_taskattachm_uploaded_by_id_57bed9e1_fk_users_use FOREIGN KEY (uploaded_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_taskattachment projects_taskattachment_task_id_70f581ad_fk_projects_task_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_taskattachment
    ADD CONSTRAINT projects_taskattachment_task_id_70f581ad_fk_projects_task_id FOREIGN KEY (task_id) REFERENCES public.projects_task(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_taskcomment projects_taskcomment_author_id_464e8986_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_taskcomment
    ADD CONSTRAINT projects_taskcomment_author_id_464e8986_fk_users_user_id FOREIGN KEY (author_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_taskcomment projects_taskcomment_task_id_3c75a98e_fk_projects_task_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.projects_taskcomment
    ADD CONSTRAINT projects_taskcomment_task_id_3c75a98e_fk_projects_task_id FOREIGN KEY (task_id) REFERENCES public.projects_task(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: teams_team teams_team_created_by_id_4d452be8_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.teams_team
    ADD CONSTRAINT teams_team_created_by_id_4d452be8_fk_users_user_id FOREIGN KEY (created_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: teams_team teams_team_workspace_id_1c116fee_fk_workspaces_workspace_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.teams_team
    ADD CONSTRAINT teams_team_workspace_id_1c116fee_fk_workspaces_workspace_id FOREIGN KEY (workspace_id) REFERENCES public.workspaces_workspace(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: teams_teammembership teams_teammembership_team_id_2ee7a456_fk_teams_team_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.teams_teammembership
    ADD CONSTRAINT teams_teammembership_team_id_2ee7a456_fk_teams_team_id FOREIGN KEY (team_id) REFERENCES public.teams_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: teams_teammembership teams_teammembership_user_id_0cb613d1_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.teams_teammembership
    ADD CONSTRAINT teams_teammembership_user_id_0cb613d1_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_users_use FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_emailverification users_emailverification_user_id_77445bf4_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_emailverification
    ADD CONSTRAINT users_emailverification_user_id_77445bf4_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_socialaccount users_socialaccount_user_id_986a64c3_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_socialaccount
    ADD CONSTRAINT users_socialaccount_user_id_986a64c3_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workspaces_auditlog workspaces_auditlog_actor_id_bb4bcbea_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_auditlog
    ADD CONSTRAINT workspaces_auditlog_actor_id_bb4bcbea_fk_users_user_id FOREIGN KEY (actor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workspaces_auditlog workspaces_auditlog_workspace_id_4ad0271b_fk_workspace; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_auditlog
    ADD CONSTRAINT workspaces_auditlog_workspace_id_4ad0271b_fk_workspace FOREIGN KEY (workspace_id) REFERENCES public.workspaces_workspace(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workspaces_workspaceinvitation workspaces_workspace_invited_by_id_9d28f43e_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_workspaceinvitation
    ADD CONSTRAINT workspaces_workspace_invited_by_id_9d28f43e_fk_users_use FOREIGN KEY (invited_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workspaces_workspace workspaces_workspace_owner_id_d8b120c0_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_workspace
    ADD CONSTRAINT workspaces_workspace_owner_id_d8b120c0_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workspaces_workspacemember workspaces_workspace_workspace_id_60079244_fk_workspace; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_workspacemember
    ADD CONSTRAINT workspaces_workspace_workspace_id_60079244_fk_workspace FOREIGN KEY (workspace_id) REFERENCES public.workspaces_workspace(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workspaces_workspaceinvitation workspaces_workspace_workspace_id_dcec2b3d_fk_workspace; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_workspaceinvitation
    ADD CONSTRAINT workspaces_workspace_workspace_id_dcec2b3d_fk_workspace FOREIGN KEY (workspace_id) REFERENCES public.workspaces_workspace(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workspaces_workspacemember workspaces_workspacemember_user_id_e5e4373e_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: zeal
--

ALTER TABLE ONLY public.workspaces_workspacemember
    ADD CONSTRAINT workspaces_workspacemember_user_id_e5e4373e_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict XnDjLtjSSTRTgdtapRtazuzETF1OGekTch4ffr8wHgl8T533hp2mFILcfHG2hfB

