# Generated by Django 4.2.30 on 2026-07-28 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_tag_document_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', '-updated_at'], name='doc_workspace_time_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', '-updated_at'], name='doc_owner_time_idx'),
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.document'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='documents.comment'),
        ),
        migrations.AddIndex(
            model_name='documentrevision',
            index=models.Index(fields=['document', '-version'], name='revision_doc_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='unique_document_revision'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['document', 'is_resolved', '-created_at'], name='comment_doc_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(('body', ''), _negated=True), name='comment_body_not_empty'),
        ),
    ]
